chain_auth_token: replace-with-a-strong-secret
chain_rpc_user: replace-with-an-rpc-user
chain_rpc_password: replace-with-a-strong-secret
chain_port: 8333
chain_web_address: replace-with-web-address
chain_web_port: 4567
